WUX.RES.OK = 'OK';
WUX.RES.CLOSE = 'Chiudi';
WUX.RES.CANCEL = 'Annulla';
WUX.RES.ERR_DATE = 'Data non ammessa.';
WUX.RES.FILE_NAME = 'File';
WUX.RES.FILE_SIZE = 'Dim.';
WUX.RES.FILE_TYPE = 'Tipo';
WUX.RES.FILE_LMOD = 'Ult.Mod.';
var GUI;
(function (GUI) {
    var WIcon = WUX.WIcon;
    var TXT = (function () {
        function TXT() {
        }
        TXT.OK = 'OK';
        TXT.CLOSE = 'Chiudi';
        TXT.NEW = 'Nuovo';
        TXT.OPEN = 'Modifica';
        TXT.DELETE = 'Elimina';
        TXT.SAVE = 'Salva';
        TXT.SEND = 'Invia';
        TXT.SEND_EMAIL = 'Email';
        TXT.FIND = 'Cerca';
        TXT.FORCE = 'Forza';
        TXT.SEARCH = 'Cerca';
        TXT.CANCEL = 'Annulla';
        TXT.RESET = 'Annulla';
        TXT.PRINT = 'Stampa';
        TXT.PRINT_ALL = 'Stampa Tutto';
        TXT.PREVIEW = 'Anteprima';
        TXT.EXPORT = 'Esporta';
        TXT.IMPORT = 'Importa';
        TXT.HELP = 'Guida';
        TXT.VIEW = 'Vedi';
        TXT.ENABLE = 'Abilita';
        TXT.DISABLE = 'Disabilita';
        TXT.ADD = 'Aggiungi';
        TXT.APPLY = 'Applica';
        TXT.REMOVE = 'Rimuovi';
        TXT.REMOVE_ALL = 'Rim.Tutto';
        TXT.REFRESH = 'Aggiorna';
        TXT.UNDO = 'Annulla';
        TXT.SETTINGS = 'Impostazioni';
        TXT.COPY = 'Copia';
        TXT.CUT = 'Taglia';
        TXT.PASTE = 'Incolla';
        TXT.CONFIRM = 'Conferma';
        TXT.FORWARD = 'Avanti';
        TXT.BACKWARD = 'Indietro';
        TXT.NEXT = 'Prossimo';
        TXT.PREVIOUS = 'Precedente';
        TXT.SELECT = 'Seleziona';
        TXT.SELECT_ALL = 'Sel.Tutto';
        TXT.WORK = 'Lavora';
        TXT.AGGREGATE = 'Aggrega';
        TXT.SET = 'Imposta';
        TXT.DEFAULT = 'Predefinito';
        TXT.REWORK = 'Rielabora';
        TXT.PUSH = 'Spedisci';
        TXT.SUSPEND = 'Sospendi';
        TXT.RESUME = 'Riattiva';
        TXT.CODE = 'Codice';
        TXT.DESCRIPTION = 'Descrizione';
        TXT.GROUP = 'Gruppo';
        TXT.ROLE = 'Ruolo';
        TXT.TYPE = 'Tipo';
        TXT.HELLO = 'Ciao';
        return TXT;
    }());
    GUI.TXT = TXT;
    var MSG = (function () {
        function MSG() {
        }
        MSG.CONF_DELETE = 'Eliminare l\'elemento selezionato?';
        MSG.CONF_DISABLE = 'Disabilitare l\'elemento selezionato?';
        MSG.CONF_ENABLE = 'Abilitare l\'elemento selezionato?';
        MSG.CONF_CANCEL = 'Si vogliono annullare le modifiche apportate?';
        MSG.CONF_PROCEED = 'Si vuole procedere con l\'operazione?';
        MSG.CONF_OVERWRITE = 'Si vuole procedere con la sovrascrittura?';
        MSG.MSG_COMPLETED = 'Operazione completata con successo.';
        MSG.MSG_ERRORS = 'Errore durante l\'elaborazione.';
        return MSG;
    }());
    GUI.MSG = MSG;
    var ICO = (function () {
        function ICO() {
        }
        ICO.TRUE = WIcon.CHECK_SQUARE_O;
        ICO.FALSE = WIcon.SQUARE_O;
        ICO.CLOSE = WIcon.TIMES;
        ICO.OK = WIcon.CHECK;
        ICO.CALENDAR = WIcon.CALENDAR;
        ICO.AGGREGATE = WIcon.CHAIN;
        ICO.NEW = WIcon.PLUS_SQUARE_O;
        ICO.EDIT = WIcon.EDIT;
        ICO.OPEN = WIcon.EDIT;
        ICO.DELETE = WIcon.TRASH;
        ICO.DETAIL = WIcon.FILE_TEXT_O;
        ICO.SAVE = WIcon.CHECK;
        ICO.FIND = WIcon.SEARCH;
        ICO.FIND_DIFF = WIcon.SEARCH_MINUS;
        ICO.FIND_PLUS = WIcon.SEARCH_PLUS;
        ICO.FORCE = WIcon.CHECK_CIRCLE;
        ICO.FORCE_ALL = WIcon.CHECK_CIRCLE_O;
        ICO.SEARCH = WIcon.SEARCH;
        ICO.CANCEL = WIcon.UNDO;
        ICO.RESET = WIcon.TIMES_CIRCLE;
        ICO.PRINT = WIcon.PRINT;
        ICO.PREVIEW = WIcon.SEARCH_PLUS;
        ICO.EXPORT = WIcon.SHARE_SQUARE_O;
        ICO.IMPORT = WIcon.SIGN_IN;
        ICO.FILE = WIcon.FILE_O;
        ICO.HELP = WIcon.QUESTION_CIRCLE;
        ICO.VIEW = WIcon.FILE_TEXT_O;
        ICO.ENABLE = WIcon.THUMBS_O_UP;
        ICO.DISABLE = WIcon.THUMBS_O_DOWN;
        ICO.ADD = WIcon.PLUS;
        ICO.APPLY = WIcon.CHECK;
        ICO.REMOVE = WIcon.MINUS;
        ICO.REFRESH = WIcon.REFRESH;
        ICO.UNDO = WIcon.UNDO;
        ICO.SETTINGS = WIcon.COG;
        ICO.OPTIONS = WIcon.CHECK_SQUARE;
        ICO.PASSWORD = WIcon.UNDO;
        ICO.COPY = WIcon.COPY;
        ICO.CUT = WIcon.CUT;
        ICO.PASTE = WIcon.PASTE;
        ICO.FORWARD = WIcon.ANGLE_DOUBLE_RIGHT;
        ICO.BACKWARD = WIcon.ANGLE_DOUBLE_LEFT;
        ICO.NEXT = WIcon.FORWARD;
        ICO.PREVIOUS = WIcon.BACKWARD;
        ICO.CONFIRM = WIcon.CHECK;
        ICO.FILTER = WIcon.FILTER;
        ICO.SEND = WIcon.SEND;
        ICO.SEND_EMAIL = WIcon.ENVELOPE_O;
        ICO.WAIT = WIcon.COG;
        ICO.WORK = WIcon.COG;
        ICO.CONFIG = WIcon.COG;
        ICO.LEFT = WIcon.ARROW_CIRCLE_LEFT;
        ICO.RIGHT = WIcon.ARROW_CIRCLE_RIGHT;
        ICO.SELECT_ALL = WIcon.TH_LIST;
        ICO.REWORK = WIcon.REFRESH;
        ICO.PUSH = WIcon.TRUCK;
        ICO.AHEAD = WIcon.ANGLE_DOUBLE_RIGHT;
        ICO.SUSPEND = WIcon.TOGGLE_OFF;
        ICO.RESUME = WIcon.RECYCLE;
        ICO.PAIRING = WIcon.RANDOM;
        ICO.CHECK = WIcon.CHECK_SQUARE_O;
        ICO.EVENT = WIcon.BOLT;
        ICO.MESSAGE = WIcon.ENVELOPE_O;
        ICO.USER = WIcon.USER_O;
        ICO.GROUP = WIcon.USERS;
        ICO.TOOL = WIcon.WRENCH;
        ICO.DEMOGRAPHIC = WIcon.ADDRESS_CARD;
        ICO.DOCUMENT = WIcon.FILE_TEXT_O;
        ICO.LINKS = WIcon.CHAIN;
        ICO.WARNING = WIcon.WARNING;
        ICO.INFO = WIcon.INFO_CIRCLE;
        ICO.CRITICAL = WIcon.TIMES_CIRCLE;
        return ICO;
    }());
    GUI.ICO = ICO;
    function formatMonth(m, e, y) {
        if (m > 100) {
            y = Math.floor(m / 100);
            m = m % 100;
        }
        y = y ? ' ' + y : '';
        switch (m) {
            case 1: return e ? 'Gennaio' + y : 'Gen' + y;
            case 2: return e ? 'Febbraio' + y : 'Feb' + y;
            case 3: return e ? 'Marzo' + y : 'Mar' + y;
            case 4: return e ? 'Aprile' + y : 'Apr' + y;
            case 5: return e ? 'Maggio' + y : 'Mag' + y;
            case 6: return e ? 'Giugno' + y : 'Giu' + y;
            case 7: return e ? 'Luglio' + y : 'Lug' + y;
            case 8: return e ? 'Agosto' + y : 'Ago' + y;
            case 9: return e ? 'Settembre' + y : 'Set' + y;
            case 10: return e ? 'Ottobre' + y : 'Ott' + y;
            case 11: return e ? 'Novembre' + y : 'Nov' + y;
            case 12: return e ? 'Dicembre' + y : 'Dic' + y;
        }
        return '';
    }
    GUI.formatMonth = formatMonth;
})(GUI || (GUI = {}));
var GUI;
(function (GUI) {
    var I18 = (function () {
        function I18() {
        }
        I18.L_NAME = 'Nome';
        I18.L_FAML = 'Cognome';
        I18.L_BIDT = 'Data di nascita';
        I18.L_CODE = 'Codice';
        I18.L_PHON = 'Telefono';
        I18.L_MAIL = 'Email';
        I18.L_TIT = 'Titolo';
        I18.L_DET = 'Dettaglio';
        I18.L_FILT = 'Filtro';
        I18.L_DESC = 'Descrizione';
        I18.L_FARE = 'Tariffa';
        I18.L_TYPE = 'Tipo';
        I18.L_AGRE = 'Convenzionata';
        I18.L_DATE = 'Data';
        I18.L_SERV = 'Prestazione';
        I18.L_STRU = 'Struttura';
        I18.L_PATH = 'Patologia';
        I18.L_EVNS = 'Eventi';
        I18.L_MONT = 'Mese';
        I18.L_DONE = 'Eseguito';
        I18.L_VALU = 'Valore';
        I18.L_COMP = 'Composizione';
        I18.L_TREN = 'Andamento';
        I18.M_SEL = 'Selezionare l\'elemento da modificare.';
        I18.M_MAND = 'Specificare';
        I18.M_MOD = 'Cliccare sul pulsante Modifica.';
        I18.M_OK = 'Operazione eseguita con successo.';
        I18.M_KO = 'Operazione non eseguita.';
        I18.M_EDIT = 'Elemento in fase di modifica.';
        I18.M_CRIT = 'Specificare almeno un criterio di ricerca.';
        I18.M_NFND = 'Nessun elemento trovato.';
        I18.M_IFND = 'elementi trovati.';
        I18.M_ALRP = 'Elemento già presente.';
        return I18;
    }());
    GUI.I18 = I18;
})(GUI || (GUI = {}));
//# sourceMappingURL=res-it.js.map