WUX.RES.OK = 'OK';
WUX.RES.CLOSE = 'Fermez';
WUX.RES.CANCEL = 'Annulez';
WUX.RES.ERR_DATE = 'Date non autorisée.';
WUX.RES.FILE_NAME = 'Fichier';
WUX.RES.FILE_SIZE = 'Dim.';
WUX.RES.FILE_TYPE = 'Type';
WUX.RES.FILE_LMOD = 'Der.Mod.';
var GUI;
(function (GUI) {
    var WIcon = WUX.WIcon;
    var TXT = (function () {
        function TXT() {
        }
        TXT.OK = 'OK';
        TXT.CLOSE = 'Fermez';
        TXT.NEW = 'Nouvel';
        TXT.OPEN = 'Modifier';
        TXT.DELETE = 'Effacer';
        TXT.SAVE = 'Enregistrez';
        TXT.SEND = 'Soumettez';
        TXT.SEND_EMAIL = 'Email';
        TXT.FIND = 'Recherchez';
        TXT.FORCE = 'Forcer';
        TXT.SEARCH = 'Recherchez';
        TXT.CANCEL = 'Annulez';
        TXT.RESET = 'Annulez';
        TXT.PRINT = 'Imprimez';
        TXT.PRINT_ALL = 'Tout imprimer';
        TXT.PREVIEW = 'Aperçu';
        TXT.EXPORT = 'Exportation';
        TXT.IMPORT = 'Importer';
        TXT.HELP = 'Aide';
        TXT.VIEW = 'Voir';
        TXT.ENABLE = 'Activer';
        TXT.DISABLE = 'Désactiver';
        TXT.ADD = 'Ajouter';
        TXT.APPLY = 'Appliquer';
        TXT.REMOVE = 'Retirer';
        TXT.REMOVE_ALL = 'Tout supprimer';
        TXT.REFRESH = 'Rafraîchir';
        TXT.UNDO = 'Annuler';
        TXT.SETTINGS = 'Réglages';
        TXT.COPY = 'Copiez';
        TXT.CUT = 'Couper';
        TXT.PASTE = 'Coller';
        TXT.CONFIRM = 'Confirmez';
        TXT.FORWARD = 'Suivant';
        TXT.BACKWARD = 'En arrière';
        TXT.NEXT = 'Le prochain';
        TXT.PREVIOUS = 'Le précédent';
        TXT.SELECT = 'Sélectionner';
        TXT.SELECT_ALL = 'Tout sél.';
        TXT.WORK = 'Travailler';
        TXT.AGGREGATE = 'Agrégat';
        TXT.SET = 'Configurer';
        TXT.DEFAULT = 'Default';
        TXT.REWORK = 'Retravailler';
        TXT.PUSH = 'Soumettre';
        TXT.SUSPEND = 'Suspendre';
        TXT.RESUME = 'Restaurer';
        TXT.CODE = 'Code';
        TXT.DESCRIPTION = 'Description';
        TXT.GROUP = 'Groupe';
        TXT.ROLE = 'Rôle';
        TXT.TYPE = 'Type';
        TXT.HELLO = 'Salut';
        return TXT;
    }());
    GUI.TXT = TXT;
    var MSG = (function () {
        function MSG() {
        }
        MSG.CONF_DELETE = 'Voulez-vous supprimer l\'élément sélectionné?';
        MSG.CONF_DISABLE = 'Voulez-vous désactiver l\'élément sélectionné?';
        MSG.CONF_ENABLE = 'Voulez-vous activer l\'élément sélectionné?';
        MSG.CONF_CANCEL = 'Voulez-vous annuler les modifications?';
        MSG.CONF_PROCEED = 'Voulez-vous continuer l\'opération?';
        MSG.CONF_OVERWRITE = 'Voulez-vous procéder à l\'écrasement?';
        MSG.MSG_COMPLETED = 'Opération terminée avec succès.';
        MSG.MSG_ERRORS = 'Erreur lors du traitement.';
        return MSG;
    }());
    GUI.MSG = MSG;
    var ICO = (function () {
        function ICO() {
        }
        ICO.TRUE = WIcon.CHECK_SQUARE_O;
        ICO.FALSE = WIcon.SQUARE_O;
        ICO.CLOSE = WIcon.TIMES;
        ICO.OK = WIcon.CHECK;
        ICO.CALENDAR = WIcon.CALENDAR;
        ICO.AGGREGATE = WIcon.CHAIN;
        ICO.NEW = WIcon.PLUS_SQUARE_O;
        ICO.EDIT = WIcon.EDIT;
        ICO.OPEN = WIcon.EDIT;
        ICO.DELETE = WIcon.TRASH;
        ICO.DETAIL = WIcon.FILE_TEXT_O;
        ICO.SAVE = WIcon.CHECK;
        ICO.FIND = WIcon.SEARCH;
        ICO.FIND_DIFF = WIcon.SEARCH_MINUS;
        ICO.FIND_PLUS = WIcon.SEARCH_PLUS;
        ICO.FORCE = WIcon.CHECK_CIRCLE;
        ICO.FORCE_ALL = WIcon.CHECK_CIRCLE_O;
        ICO.SEARCH = WIcon.SEARCH;
        ICO.CANCEL = WIcon.UNDO;
        ICO.RESET = WIcon.TIMES_CIRCLE;
        ICO.PRINT = WIcon.PRINT;
        ICO.PREVIEW = WIcon.SEARCH_PLUS;
        ICO.EXPORT = WIcon.SHARE_SQUARE_O;
        ICO.IMPORT = WIcon.SIGN_IN;
        ICO.FILE = WIcon.FILE_O;
        ICO.HELP = WIcon.QUESTION_CIRCLE;
        ICO.VIEW = WIcon.FILE_TEXT_O;
        ICO.ENABLE = WIcon.THUMBS_O_UP;
        ICO.DISABLE = WIcon.THUMBS_O_DOWN;
        ICO.ADD = WIcon.PLUS;
        ICO.APPLY = WIcon.CHECK;
        ICO.REMOVE = WIcon.MINUS;
        ICO.REFRESH = WIcon.REFRESH;
        ICO.UNDO = WIcon.UNDO;
        ICO.SETTINGS = WIcon.COG;
        ICO.OPTIONS = WIcon.CHECK_SQUARE;
        ICO.PASSWORD = WIcon.UNDO;
        ICO.COPY = WIcon.COPY;
        ICO.CUT = WIcon.CUT;
        ICO.PASTE = WIcon.PASTE;
        ICO.FORWARD = WIcon.ANGLE_DOUBLE_RIGHT;
        ICO.BACKWARD = WIcon.ANGLE_DOUBLE_LEFT;
        ICO.NEXT = WIcon.FORWARD;
        ICO.PREVIOUS = WIcon.BACKWARD;
        ICO.CONFIRM = WIcon.CHECK;
        ICO.FILTER = WIcon.FILTER;
        ICO.SEND = WIcon.SEND;
        ICO.SEND_EMAIL = WIcon.ENVELOPE_O;
        ICO.WAIT = WIcon.COG;
        ICO.WORK = WIcon.COG;
        ICO.CONFIG = WIcon.COG;
        ICO.LEFT = WIcon.ARROW_CIRCLE_LEFT;
        ICO.RIGHT = WIcon.ARROW_CIRCLE_RIGHT;
        ICO.SELECT_ALL = WIcon.TH_LIST;
        ICO.REWORK = WIcon.REFRESH;
        ICO.PUSH = WIcon.TRUCK;
        ICO.AHEAD = WIcon.ANGLE_DOUBLE_RIGHT;
        ICO.SUSPEND = WIcon.TOGGLE_OFF;
        ICO.RESUME = WIcon.RECYCLE;
        ICO.PAIRING = WIcon.RANDOM;
        ICO.CHECK = WIcon.CHECK_SQUARE_O;
        ICO.EVENT = WIcon.BOLT;
        ICO.MESSAGE = WIcon.ENVELOPE_O;
        ICO.USER = WIcon.USER_O;
        ICO.GROUP = WIcon.USERS;
        ICO.TOOL = WIcon.WRENCH;
        ICO.DEMOGRAPHIC = WIcon.ADDRESS_CARD;
        ICO.DOCUMENT = WIcon.FILE_TEXT_O;
        ICO.LINKS = WIcon.CHAIN;
        ICO.WARNING = WIcon.WARNING;
        ICO.INFO = WIcon.INFO_CIRCLE;
        ICO.CRITICAL = WIcon.TIMES_CIRCLE;
        return ICO;
    }());
    GUI.ICO = ICO;
    function formatMonth(m, e, y) {
        if (m > 100) {
            y = Math.floor(m / 100);
            m = m % 100;
        }
        y = y ? ' ' + y : '';
        switch (m) {
            case 1: return e ? 'Janvier' + y : 'Jan' + y;
            case 2: return e ? 'Février' + y : 'Fév' + y;
            case 3: return e ? 'Mars' + y : 'Mar' + y;
            case 4: return e ? 'Avril' + y : 'Avr' + y;
            case 5: return e ? 'Mai' + y : 'Mai' + y;
            case 6: return e ? 'Juin' + y : 'Jui' + y;
            case 7: return e ? 'Juillet' + y : 'Jul' + y;
            case 8: return e ? 'Août' + y : 'Aoû' + y;
            case 9: return e ? 'Septembre' + y : 'Sep' + y;
            case 10: return e ? 'Octobre' + y : 'Oct' + y;
            case 11: return e ? 'Novembre' + y : 'Nov' + y;
            case 12: return e ? 'Décembre' + y : 'Déc' + y;
        }
        return '';
    }
    GUI.formatMonth = formatMonth;
})(GUI || (GUI = {}));
var GUI;
(function (GUI) {
    var I18 = (function () {
        function I18() {
        }
        I18.L_NAME = 'Prénom';
        I18.L_FAML = 'Nom';
        I18.L_BIDT = 'Date de naissance';
        I18.L_CODE = 'Code';
        I18.L_PHON = 'Téléphone';
        I18.L_MAIL = 'Email';
        I18.L_TIT = 'Titre';
        I18.L_DET = 'Détail';
        I18.L_FILT = 'Filtre';
        I18.L_DESC = 'Description';
        I18.L_FARE = 'Tarif';
        I18.L_TYPE = 'Type';
        I18.L_AGRE = 'Accord';
        I18.L_DATE = 'Date';
        I18.L_SERV = 'Prestation';
        I18.L_STRU = 'Structure';
        I18.L_PATH = 'Pathologie';
        I18.L_EVNS = 'Événements';
        I18.L_MONT = 'Mois';
        I18.L_DONE = 'Fini';
        I18.L_VALU = 'Valeur';
        I18.L_COMP = 'Composition';
        I18.L_TREN = 'Tendance';
        I18.M_SEL = 'Sélectionnez l\'élément à modifier.';
        I18.M_MAND = 'Indiquer';
        I18.M_MOD = 'Cliquez sur le bouton Modifier.';
        I18.M_OK = 'Opération réalisée avec succès.';
        I18.M_KO = 'Opération non effectuée.';
        I18.M_EDIT = 'Élément en cours de modification.';
        I18.M_CRIT = 'Spécifiez au moins un critère de recherche.';
        I18.M_NFND = 'Aucun élément trouvé.';
        I18.M_IFND = 'éléments trouvés.';
        I18.M_ALRP = 'Élément déjà présent.';
        return I18;
    }());
    GUI.I18 = I18;
})(GUI || (GUI = {}));
//# sourceMappingURL=res-fr.js.map